# Merged custom Q&A into one final dictionary
custom_answers = {
    # India GK
    "what is the national anthem of india": "The national anthem of India is Jana Gana Mana, written by Rabindranath Tagore.",
    "india's national anthem": "The national anthem of India is Jana Gana Mana.",
    "who wrote the indian national anthem": "The Indian national anthem was written by Rabindranath Tagore.",
    "what is the national song of india": "The national song of India is Vande Mataram, composed by Bankim Chandra Chatterjee.",
    "what is the national bird of india": "The national bird of India is the Indian Peacock.",
    "what is the national animal of india": "The national animal of India is the Bengal Tiger.",
    

    "who built the taj mahal": "The Taj Mahal was built by Mughal Emperor Shah Jahan in memory of his wife Mumtaz Mahal.",
    "who build taj mahal": "The Taj Mahal was built by Mughal Emperor Shah Jahan in memory of his wife Mumtaz Mahal.",

     
    "what is the national anthem of india": "Jana Gana Mana, written by Rabindranath Tagore.",
    
    "what is the name of the indian national anthem": "The national anthem of India is 'Jana Gana Mana', written by Rabindranath Tagore.",


    "what is the national flower of india": "The national flower of India is the Lotus.",
    "what is the national fruit of india": "The national fruit of India is Mango.",
    "what is the national game of india": "Hockey is often considered the national game of India, though it's not officially declared.",
    "what is the national tree of india": "The national tree of India is the Banyan tree.",
    "what is the capital of india": "The capital of India is New Delhi.",
    "who is the prime minister of india": "The current Prime Minister of India is Narendra Modi.",
    "who is the president of india": "The current President of India is Droupadi Murmu.",
    "what is the currency of india": "The currency of India is the Indian Rupee (INR).",
    "how many states are there in india": "India has 28 states and 8 Union territories.",
    "what is the national flag of india": "The national flag of India is a tricolor with saffron, white, and green, with a blue Ashoka Chakra in the center.",
    "what is the national emblem of india": "The national emblem of India is an adaptation of the Lion Capital of Ashoka.",
    "what is the national motto of india": "The national motto of India is 'Satyameva Jayate' meaning 'Truth Alone Triumphs'.",
    "who is the father of the nation": "Mahatma Gandhi is known as the Father of the Nation in India.",
    "when is independence day celebrated in india": "Independence Day is celebrated on August 15th every year in India.",
    "who is the current cm of andhra pradesh": "N. Chandrababu Naidu",
    "who is the governor of andhra pradesh": "S. Abdul Nazeer",
    "who is the cm of andhra pradesh": "The current Chief Minister of Andhra Pradesh is N. Chandrababu Naidu.",
    "who is the present cm of ap": "N. Chandrababu Naidu is the present Chief Minister of Andhra Pradesh.",
    "current chief minister of ap": "N. Chandrababu Naidu is the current Chief Minister of Andhra Pradesh.",
    "chief minister of ap 2024": "As of 2024, the Chief Minister of Andhra Pradesh is N. Chandrababu Naidu.",

    # Other Indian states CMs
    "who is the cm of telangana": "The Chief Minister of Telangana is Revanth Reddy.",
    "who is the cm of tamil nadu": "The Chief Minister of Tamil Nadu is M. K. Stalin.",
    "who is the cm of maharashtra": "The Chief Minister of Maharashtra is Eknath Shinde.",
    "who is the cm of karnataka": "The Chief Minister of Karnataka is Siddaramaiah.",
    "who is the cm of uttar pradesh": "The Chief Minister of Uttar Pradesh is Yogi Adityanath.",
    "who is the cm of bihar": "The Chief Minister of Bihar is Nitish Kumar.",
    "who is the cm of west bengal": "The Chief Minister of West Bengal is Mamata Banerjee.",
    "who is the cm of gujarat": "The Chief Minister of Gujarat is Bhupendrabhai Patel.",


    # World GK
    "what is the capital of usa": "Washington, D.C.",
    "capital of france": "Paris",
    "capital of japan": "Tokyo",
    "capital of russia": "Moscow",
    "currency of japan": "Yen",
    "currency of usa": "Dollar",
    "largest country in the world": "Russia",
    "smallest country in the world": "Vatican City",
    "who discovered america": "Christopher Columbus",
    "who is the president of usa": "Joe Biden",
    

    # Science & Tech
    "what is the speed of light": "Approximately 299,792 kilometers per second.",
    "what is gravity": "A force that attracts objects towards each other.",
    "who invented the light bulb": "Thomas Edison",
    "who is the father of computer": "Charles Babbage",
    "what is a computer": "An electronic device for storing and processing data.",
    "what is ai": "Artificial Intelligence is the simulation of human intelligence in machines.",
    "what is the internet": "A global system of interconnected computer networks.",
    "what is a black hole": "A region of space with a gravitational pull so strong that nothing can escape it.",
    "what is photosynthesis": "The process by which green plants make food using sunlight.",

    # Human Body
    "how many bones in human body": "206 bones",
    "largest organ in human body": "Skin",
    "how many lungs does a human have": "Two lungs",
    "what is the function of heart": "To pump blood throughout the body.",

    # History & Culture
    "who was the first president of india": "Dr. Rajendra Prasad",
    "who was the first prime minister of india": "Jawaharlal Nehru",
    "who wrote the ramayana": "Valmiki",
    "who wrote the mahabharata": "Vyasa",
    "when did india get independence": "1947",
    "taj mahal is located in which city": "Agra",

    # Geography
    "highest mountain in the world": "Mount Everest",
    "longest river in the world": "Nile River",
    "largest desert in the world": "Sahara Desert",
    "largest ocean in the world": "Pacific Ocean",
    "where is mount everest located": "Nepal",

    # Math & Logic
    "what is pi": "Pi is a mathematical constant approximately equal to 3.14159.",
    "what is 2 plus 2": "4",
    "what is the square root of 16": "4",
    "what is 10 factorial": "3628800",

    # Literature & Arts
    "who wrote hamlet": "William Shakespeare",
    "who painted the mona lisa": "Leonardo da Vinci",
    "who wrote harry potter": "J.K. Rowling",

    # Space & Astronomy
    "how many planets in solar system": "Eight",
    "which planet is closest to the sun": "Mercury",
    "which planet is known as red planet": "Mars",
    "earth is a part of which galaxy": "Milky Way Galaxy",

    # Fun & Facts
    "fastest land animal": "Cheetah",
    "tallest animal": "Giraffe",
    "which animal is known as ship of the desert": "Camel",
    "who is known as iron man of india": "Sardar Vallabhbhai Patel",
    "which is the longest river in india": "Ganga",

    # Current Affairs (2024–2025)
    "who is the ceo of tesla": "Elon Musk",
    "who is the ceo of google": "Sundar Pichai"
}


custom_answers = {
    "what is the national anthem of india": "The national anthem of India is Jana Gana Mana.",
    "who wrote the indian constitution": "Dr. B. R. Ambedkar is known as the Father of the Indian Constitution.",
    "when did india become a republic": "India became a republic on January 26, 1950.",
    "who is known as the missile man of india": "Dr. A. P. J. Abdul Kalam",
    "what is the national calendar of india": "The national calendar of India is the Saka Calendar.",
    "who was the first woman prime minister of india": "Indira Gandhi",
    "who is the founder of indian national congress": "A. O. Hume",
    "how many union territories are there in india": "There are 8 Union Territories in India.",
    "which city is known as pink city": "Jaipur",
    "which indian state has the longest coastline": "Gujarat",
    "what is the national river of india": "The Ganga is considered the National River of India.",
    "what is the national heritage animal of india": "The Indian Elephant",
    "who was the first president of india": "Dr. Rajendra Prasad",
    "who was the first prime minister of india": "Jawaharlal Nehru",
    "which city is known as the silicon valley of india": "Bengaluru",
    "which city is known as the city of joy": "Kolkata",
    "which city is known as the city of lakes": "Udaipur",
    "who gave the slogan 'swaraj is my birthright'": "Bal Gangadhar Tilak",
    "who is called the iron man of india": "Sardar Vallabhbhai Patel",
    "who was the first woman president of india": "Pratibha Patil",
    "which is the smallest state in india by area": "Goa",
    "which is the largest state in india by area": "Rajasthan",
    "which indian state is known as the spice garden": "Kerala",
    "who is the first indian to win a nobel prize": "Rabindranath Tagore",
    "when is republic day celebrated in india": "Republic Day is celebrated on January 26th.",
    "when is independence day celebrated in india": "Independence Day is celebrated on August 15th.",
    "who wrote vande mataram": "Bankim Chandra Chatterjee",
    "which animal is the national aquatic animal of india": "The Ganges River Dolphin",
    "what is the national fruit of india": "Mango",
    "what is the national flower of india": "Lotus",
    "what is the national animal of india": "Bengal Tiger",
    "what is the national bird of india": "Indian Peacock",
    "what is the national tree of india": "Banyan Tree",
    "what is the national emblem of india": "The Lion Capital of Ashoka",
    "what is the national game of india": "Field Hockey (unofficially considered)",
    "what is the national song of india": "Vande Mataram",
    "what is the capital of india": "New Delhi",
    "who is the current prime minister of india": "Narendra Modi",
    "who is the current president of india": "Droupadi Murmu",
    "who was the first indian in space": "Rakesh Sharma",
    "which indian city is called the city of temples": "Bhubaneswar",
    "which is the longest river in india": "The Ganges (Ganga)",
    "which is the highest civilian award in india": "Bharat Ratna",
    "who was the first female ips officer of india": "Kiran Bedi",
    "what is the indian currency": "Indian Rupee (INR)",
    "who is known as the nightingale of india": "Sarojini Naidu",
    "which city is known as the steel city of india": "Jamshedpur",
    "which indian city is known as the diamond city": "Surat",
    "which state is called the land of five rivers": "Punjab",
    "who gave the slogan 'quit india'": "Mahatma Gandhi",
    "who was the first indian woman to go to space": "Kalpana Chawla",
    "which festival is known as the festival of colors": "Holi",
    "which is the highest peak in india": "Kangchenjunga",
    "which place is known as the paradise on earth": "Kashmir",
    "which state is known as the land of rising sun in india": "Arunachal Pradesh",
    "who was the first governor-general of independent india": "Lord Mountbatten",
    "which state is famous for its backwaters": "Kerala",
    "which city is known as the blue city of india": "Jodhpur",
    "what is the full form of isro": "Indian Space Research Organisation",
    "who is the founder of isro": "Dr. Vikram Sarabhai",
    "who is known as the father of green revolution in india": "M. S. Swaminathan",
    "what is the full form of drdo": "Defence Research and Development Organisation",
    "which is the most populated state in india": "Uttar Pradesh",
    "which is the cleanest city in india": "Indore",
    "who was the last governor-general of india": "C. Rajagopalachari",
    "which state is known as the land of festivals": "Nagaland",
    "what is the national motto of india": "'Satyameva Jayate' meaning 'Truth Alone Triumphs'",
    "which is the largest port in india": "Jawaharlal Nehru Port (Nhava Sheva)",
    "which indian city is known as the garden city": "Bengaluru",
    "which indian monument is known as a symbol of love": "Taj Mahal",
    "who built the red fort": "Shah Jahan",
    "what is the oldest language in india": "Tamil",
    "what is the largest museum in india": "Indian Museum, Kolkata",
    "who is the current chief justice of india": "Dhananjaya Y. Chandrachud",
    "what is the national education policy 2020": "It is a policy introduced to overhaul India's education system, replacing NEP 1986.",
    "which indian city hosted g20 summit 2023": "New Delhi",
    "what is the largest dam in india": "Tehri Dam",
    "which river is called the dakshina ganga": "Godavari",
    "which indian scientist won nobel prize for physics in 1930": "C. V. Raman",
    "who is known as the flying sikh": "Milkha Singh",
    "what is the minimum voting age in india": "18 years",
    "what is the indian space mission to the moon called": "Chandrayaan",
    "which state is famous for bihu festival": "Assam",
    "which is the largest stadium in india": "Narendra Modi Stadium",
    "which city is known as the coal capital of india": "Dhanbad",
    "who is known as the father of indian cinema": "Dadasaheb Phalke",
    "which is the largest zoo in india": "Arignar Anna Zoological Park, Chennai",
    "what is the main crop of india": "Rice",
    "which dance is classical dance of odisha": "Odissi",
    "which river is called the sorrow of bengal": "Damodar River",
    "which place is known for its silk production": "Kanchipuram",
    "which indian state has the highest literacy rate": "Kerala",
    "which is the only floating national park in the world": "Keibul Lamjao National Park",
    "what is the capital of andhra pradesh": "Amaravati",
    "which city is famous for chikankari embroidery": "Lucknow",
    "which is the only active volcano in india": "Barren Island, Andaman and Nicobar Islands",
    "which city is famous for its diamond cutting industry": "Surat",
    "who is known as the father of indian nuclear program": "Homi J. Bhabha",
    "what is the headquarters of rbi": "Mumbai",
    "who was the first woman governor of an indian state": "Sarojini Naidu",
    "who was the first indian to win an olympic medal": "Norman Pritchard (1900, athletics)",
    "what is the main religion in india": "Hinduism",
    "what is the official language of india": "Hindi, with English as a subsidiary official language"
}
